kind: Deployment
apiVersion: apps/v1
metadata:
  name: notes-app-deployment
  namespace: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  
  template:
    metadata:
      name: notes-app
      labels:
        app: notes-app
     
    spec:
      containers:
      - name: notes-app
        image: pransadawarte/notes-app-k8s:latest 
        ports:
        - containerPort: 8000

